name: Dry run deploy
on:
  push:
    branches:
      - develop
      - semantic-release/*
      - feature/*
      - fix/*
      - breaking/*

jobs:
  deploy:
    environment: vsce-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci

      - name: Publish
        # for testing, add -- --dry-run --debug
        run: npm run semantic-release -- --dry-run
        env:
          VSCE_PAT: ${{ secrets.PUBLISHER_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
