name: Test Pymakr

on:
  pull_request: ~
  push:
    branches-ignore:
      - 'dependabot/**'
    paths-ignore:
      - 'doc/**'

jobs:
  build:
    name: 'Build ${{ matrix.os }}'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: install dependencies
        run: npm ci

      - if: runner.os == 'Linux'
        name: Run tests (Linux)
        run: |
          rm /home/runner/work/pymakr-vsc/pymakr-vsc/node_modules/@serialport/bindings/build/Release/bindings.node
          xvfb-run -a npm test
      - if: runner.os != 'Linux'
        name: Run tests (Mac/Win)
        run: npm test
